users: list = [
    {'name': 'Dominik', 'posts': 1, 'city': 'Siedlce'},
    {'name': 'Dominik_K', 'posts': 3, 'city': 'Poznań'},
    {'name': 'Szymon z wąsem', 'posts': 5, 'city': 'Inowrocław'},
    {'name': 'Szymon', 'posts': 7, 'city': 'Białogard'},
    {'name': 'Patryk', 'posts': 9, 'city': 'Łódź'},
    {'name': 'Żerom', 'posts': 9, 'city': 'Tarnobrzeg'},
    {'name': 'Michał', 'posts': 4, 'city': 'Kluczbork'},
    {'name': 'Kinga', 'posts': 25, 'city': 'Gdynia'},
    {'name': 'Amelia', 'posts': 32, 'city': 'Toruń'},
    {'name': 'Karolina', 'posts': 20, 'city': 'Bydgoszcz'},
    {'name': 'Julka', 'posts': 4, 'city': 'Zamość'},
    {'name': 'Ola', 'posts': 25, 'city': 'Radom'},
    {'name': 'Patrycja', 'posts': 32, 'city': 'Zielona_Góra'},
    {'name': 'Patrycja', 'posts': 20, 'city': 'Kraśnik'},
    {'name': 'Patrycja', 'posts': 20, 'city': 'Mińsk_Mazowiecki'},
]