users: list = [
    {'name': 'Michał', 'posts': 1, 'city': 'Warszawa'},
    {'name': 'Dominik', 'posts': 3, 'city': 'Poznań'},
    {'name': 'Szymon z wąsem', 'posts': 5, 'city': 'Toruń'},
    {'name': 'Szymon', 'posts': 7, 'city': 'łódź'},
    {'name': 'Patryk', 'posts': 9, 'city': 'Kielce'},
    {'name': 'Żerom', 'posts': 9, 'city': 'Kielce'},
    {'name': 'Michał', 'posts': 4, 'city': 'Kluczbork'},
    {'name': 'Kinga', 'posts': 25, 'city': 'Toruń'},
    {'name': 'Amelia', 'posts': 32, 'city': 'Bydgoszcz'},
    {'name': 'Karolina', 'posts': 20, 'city': 'Zamość'},
    {'name': 'Julka', 'posts': 4, 'city': 'Łódź'},
    {'name': 'Ola', 'posts': 25, 'city': 'Toruń'},
    {'name': 'Patrycja', 'posts': 32, 'city': 'Bydgoszcz'},
    {'name': 'Patrycja', 'posts': 20, 'city': 'Zamość'},
    {'name': 'Patrycja', 'posts': 20, 'city': 'Zamość'},
]